name: test

on: push

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    name: Smart contract tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install node dependencies
        run: yarn --frozen-lockfile

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
        run: |
          forge test -vvv
        id: test

      - name: Run Hardhat tests
        run: yarn test

      # - name: Run Slither
      #   uses: crytic/slither-action@v0.2.0
      #   with:
      #     ignore-compile: true
      #     node-version: 16
      #     fail-on: none
